### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by WaluigiBSOD** [WaluigiBSOD/fzmv-password-generator#1]
# Code

- [x] Not really urgent, but a statement in [password.js](https://github.com/WaluigiBSOD/fzmv-password-generator/blob/c1614d1c541f8f6e75b5a548491085e950b8cc81/js/password.js#L106) can be rewritten with bit shifting, mostly to be consistent with [fzmv-password-decoder](https://github.com/WaluigiBSOD/fzmv-password-decoder/blob/13a697409277fbec92b0436f2ec2ff577d1fb2df/js/password.js#L65)
- [x] Not really urgent too, but would also be a good idea to remove input clear on mouse click, fits more for just password decoders when a working password has been entered, an idea could be also moving it on right click or double click
- [x] Replace every instance of multiplication, division or remainder involving powers of 2 with their bit-wise equivalent form
- [x] `_ExistsInKeyboard1D` inside [keyboard.js](https://github.com/WaluigiBSOD/fzmv-password-generator/blob/a84bc93a520dbe90e005e3dc30c500b0d956da97/js/keyboard.js#L45) has ironically zero purpose to exist, remove it
- [x] Some calls of `_FindOffsetInKeyboard1D` in [dijkstra.js](https://github.com/WaluigiBSOD/fzmv-password-generator/blob/a84bc93a520dbe90e005e3dc30c500b0d956da97/js/dijkstra.js), [generator.js](https://github.com/WaluigiBSOD/fzmv-password-generator/blob/a84bc93a520dbe90e005e3dc30c500b0d956da97/js/generator.js), and [keyboard.js](https://github.com/WaluigiBSOD/fzmv-password-generator/blob/a84bc93a520dbe90e005e3dc30c500b0d956da97/js/keyboard.js) can be replaced with constants
- [x] In [password.js](https://github.com/WaluigiBSOD/fzmv-password-generator/blob/a84bc93a520dbe90e005e3dc30c500b0d956da97/js/password.js#L32) the check `((((Buffer[ElementX] & (1 << BitX)) >> BitX) + ((Buffer[ElementY] & (1 << BitY)) >> BitY)) & 0x1)` can be rewritten as just `(((Buffer[ElementX] & (1 << BitX)) >> BitX) ^ ((Buffer[ElementY] & (1 << BitY)) >> BitY))`
- [x] There is a typo in a comment inside [dijkstra.js](https://github.com/WaluigiBSOD/fzmv-password-generator/blob/a84bc93a520dbe90e005e3dc30c500b0d956da97/js/dijkstra.js#L112), fix it
- [x] Add an empty `.nojekyll` file in the root of the website
- [x] Add a `404.html` 404 error handler in the root of the website that redirects to the main page
